# -- Name
fullnameOverride: "example-helm-chart"

# -- Deployments
deployments:
  - name: first-deployment
    replicaCount: 1
    initContainers:
      - name: alpine
        image:
          repository: alpine
          tag: latest
        securityContext:
          readOnlyRootFilesystem: true
        args:
          - "echo"
          - "Hello World"
        env:
          - name: TEMP
            value: /tmp
        PullPolicy: IfNotPresent
    containers:
      - name: phpfpm
        image:
          repository: bitnami/php-fpm
          tag: "latest"
        pullPolicy: IfNotPresent
        securityContext:
          readOnlyRootFilesystem: false
        env:
          - name: TEMP
            value: /tmp
        ports:
          - name: php
            containerPort: 9000
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
        - name: shared-storage
          mountPath: /data/shared-storage

      - name: nginx
        image:
          repository: nginx
          tag: "latest"
        pullPolicy: IfNotPresent
        
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "date > /container-started.txt"]
          preStop:
            exec:
              command: ["/usr/sbin/nginx", "-s", "quit"]
        ports:
          - name: http
            containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
        - name: shared-storage
          mountPath: /data/shared-storage
    volumes:
    - name: shared-storage
      emptyDir: {}

  - name: second-deployment
    replicaCount: 1
    containers:
      - name: nginx
        image:
          repository: nginx
          tag: "latest"
        pullPolicy: Always
        ports:
          - name: http
            containerPort: 80
        resources: {}
       